version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  db:
    image: mongo
    restart: always
    container_name: db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: mongo
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js

  producer:
    build:
      context: ./producer
      dockerfile: Dockerfile
    restart: always
    container_name: producer
    environment:
      KAFKA_URL: kafka:9092
    ports:
      - "8082:8082"
    depends_on:
      - kafka

  consumer:
    build:
      context: ./consumer
      dockerfile: Dockerfile
    restart: always
    container_name: consumer
    environment:
      KAFKA_URL: kafka:9092
      MONGO_HOST: db
      USERNAME: user
      PASSWORD: password
    depends_on:
      - producer
      - kafka
      - db
    ports:
      - "8083:8083"