server:
  port: 8083

spring:
  kafka:
    topic:
      name: user
    consumer:
      bootstrap-servers: ${KAFKA_URL:localhost:9092,localhost:9093,localhost:9094}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  data:
    mongodb:
      port: ${MONGO_PORT:27017}
      host: ${MONGO_HOST:localhost}
      database: ${MONGO_DATABASE:mongo}
      username: ${MONGO_USERNAME:user}
      password: ${MONGO_PASSWORD:password}
