server:
  port: 8082

spring:
  kafka:
    topic:
      name: fish
      partitions: 3
    producer:
      bootstrap-servers: ${KAFKA_URL:localhost:9092,localhost:9093,localhost:9094}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer