server:
  port: 8082

spring:
  kafka:
    topic:
      name: user
      partitions: 3
    producer:
      bootstrap-servers: ${KAFKA_URL:localhost:9092}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer